name: Deploy GitHub Pages

on:
  push:
    branches:
      - main # Thay 'main' bằng nhánh bạn muốn deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          # Đường dẫn tới thư mục chứa file .html (trong trường hợp này là thư mục gốc)
          path: .
